title: /Users/romankonz/devlog
email: roman@konz.me
description: >
  my development log
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: RomanKonz
github_username: romankonz

# Build settings
markdown: kramdown
theme: minima
